(defvar sinvirt-heading "SINDACATO NAZIONALE VIRTUALE
ADERENTE AL FEDERVIRTUALI/SINTRO/CIBER")

(defvar sinvirt-default-number-of-phrases 30)

(defun my-test (&optional arg)
  (interactive)
  (if current-prefix-arg
      (message current-prefix-arg)
    (message "NO ARG")))

(defun sinvirt (&optional length)
  "Main for sinvirt hack"
  (interactive)
  (let* ((name "*sinvirt-output*")
         (buffer (get-buffer name)))
    (if buffer
        (kill-buffer name))
    (let ((length (or current-prefix-arg sinvirt-default-number-of-phrases))
          (buffer (generate-new-buffer name)))
      (with-temp-buffer
        (goto-char (point-min))
        (insert sinvirt-heading "\n\n")
        (insert (concat "COMUNICATO: " (sinvirt-title) "\n\n"))
        (insert (sinvirt-message length))
        (insert "\n\n" (sinvirt-signature) "\n\n")
        (append-to-buffer name (point-min) (point-max) ))
      (switch-to-buffer name)
      (goto-char (point-min))
      )))

(defun sinvirt-title ()
  "Title for a Sinvirt"
  (concat
   (sinvirt-select
    (sinvirt-concat (sinvirt-part-0) (sinvirt-part-1) (sinvirt-part-2) )
    (sinvirt-concat (sinvirt-part-0) (sinvirt-part-1) (sinvirt-part-6) ) ) "."))

(defun sinvirt-message (length)
  (let ((todo (or length 40))
        (text ""))
    (while (> todo 0)
      (setq text (concat text  (sinvirt-phrase)))
      (setq todo (1- todo)))
    (replace-regexp-in-string
     " \([ \.,:;!]\)" "\1" text)))

(defun sinvirt-phrase ()
  "Select phrase by models"
  (concat
   (sinvirt-select
                                        ; Model 0
    (sinvirt-select
     (sinvirt-concat (sinvirt-part-0) (sinvirt-part-1) (sinvirt-part-2) )
     (sinvirt-concat (sinvirt-part-0) (sinvirt-part-1) (sinvirt-part-6) ) )
                                        ; Model 1
    (sinvirt-select
     (sinvirt-concat
      (sinvirt-part-0) (sinvirt-part-1) (sinvirt-part-2) (sinvirt-part-5))
     (sinvirt-concat
      (sinvirt-part-0) (sinvirt-part-1) (sinvirt-part-6) (sinvirt-part-5)) )
                                        ;  Model 2
    (sinvirt-select
     (sinvirt-concat
      (sinvirt-part-0) (sinvirt-part-1) (sinvirt-part-2) (sinvirt-part-3)
      (sinvirt-part-4) (sinvirt-part-6) ) )
                                        ; Model 3
    (sinvirt-select
     (sinvirt-concat
      (sinvirt-part-0) (sinvirt-part-1) (sinvirt-part-2) (sinvirt-part-3)
      (sinvirt-part-4) (sinvirt-part-5) (sinvirt-part-6) ) ) )
   (punct) ))

(defun sinvirt-choice (phrase &optional prob)
  "If random is under prob then add phrase"
  (let ((prob (or prob .5)))
    (if (< (random 100) (* prob 100))
        phrase
      nil)))

(defun sinvirt-select (&rest alterns)
  "Select one of the alterns - same probs"
  (let* ((size (length alterns))
         (index (random size)))
    (nth index alterns)))

(defun sinvirt-join (sep lst)
  "Join with a separator"
  (mapconcat 'identity lst sep))

(defun sinvirt-concat (&rest parts)
  "Concat with a separator"
  (sinvirt-join " " parts))

(defun sinvirt-pick (rnd choices)
  "Pick one by probability"
  (let ((rand (or rnd (random 1000)))
        (el (car choices)))
    (if (< rand (* 1000 (car (cdr el))))
        (car el)
      (sinvirt-pick rand  (cdr choices) ))))

(defun punct ()
  (sinvirt-pick nil `(
                      (". "  .6)
                      (".\n\n"  .9)
                      (","  .95)
                      (";" .975)
                      (":"   .99)
                      ("!"  1.0))))

;; - This is the domain talk base phrases

(defun sinvirt-part-0 ()
  (sinvirt-select
   (sinvirt-concat "La posizione" (sinvirt-choice "iniziale") "della Banca")
   (sinvirt-concat "L'orologio" (sinvirt-choice "impazzito") "della politica")
   (sinvirt-concat (sinvirt-choice "Ad esempio," .15) "un" (sinvirt-choice "giovane" .25) "collega del servizio FCV")
   (sinvirt-concat  "L'insieme delle filiali" (sinvirt-choice "nel suo complesso" .75))
   (sinvirt-concat  "Il rispetto dell'art. 4" (sinvirt-choice "della legge 300 (\"Statuto dei Lavoratori\")" .75))
   (sinvirt-concat  "L'idea" (sinvirt-choice "principale" .95) )
   (sinvirt-concat  "Il processo" (sinvirt-choice "contorto" .15) "di valutazione personale")
   (sinvirt-concat  "La" (sinvirt-choice "stanca") "liturgia del bollettino")
   (sinvirt-concat  "La ribadita" (sinvirt-choice "ennesima") "proposta")
   (sinvirt-concat  "Il fondo complementare" )
   (sinvirt-concat  "L'istituto del part-time orizzontale" )
   (sinvirt-concat  "L'incentivazione strumentale" )
   (sinvirt-concat  "Il" (sinvirt-choice "portato del") "progetto annuale")
   (sinvirt-concat  "Il sistema" (sinvirt-choice "antiquato") "delle relazioni sindacali")
   (sinvirt-concat  "Il sindacato di maggioranza" (sinvirt-choice "relativa"))
   (sinvirt-concat  "Il sindacato di minoranza" (sinvirt-choice "relativa"))
   (sinvirt-concat  "La maggioranza sindacale" )
   (sinvirt-concat  "La minoranza sindacale" )
   (sinvirt-concat  "L'adesione dei dirigenti" (sinvirt-choice "più retrivi" .10))
   (sinvirt-concat  "Nei momenti di maggiore attività" )
   (sinvirt-concat  "La risposta" (sinvirt-choice "entusiasmante") "del personale" (sinvirt-choice "più giovane"))
   (sinvirt-concat  "La risposta" (sinvirt-choice "deprimente") "del personale" (sinvirt-choice "più giovane"))
   (sinvirt-concat  "L'utenza" (sinvirt-choice "potenziale"))
   (sinvirt-concat  "Il bisogno" (sinvirt-choice "emergente"))
   (sinvirt-concat  "Il" (sinvirt-choice "complicato") "quadro normativo")
   (sinvirt-concat  "Il rinnovo contrattuale" (sinvirt-choice "tanto atteso"))
   (sinvirt-concat  "Il nuovo soggetto sociale" )
   (sinvirt-concat  "L'approccio programmatorio" )
   (sinvirt-concat  "L'assetto politico-istituzionale" )
   (sinvirt-concat  "Il criterio metodologico" )
   (sinvirt-concat  "Il modello di sviluppo" )
   (sinvirt-concat  "Il metodo partecipativo" )
   (sinvirt-concat  "L'organizzazione moderna" )
   (sinvirt-concat  "L'efficacia gestionale" )
   (sinvirt-concat  "Il portato del Governatore attuale" )
   (sinvirt-concat  "Il trattamento di quiescenza" )
   (sinvirt-concat  "Il cumulo pensionistico" )
   (sinvirt-concat  "Il lavoro notturno" )
   (sinvirt-concat  "La polizza sanitaria" )
   (sinvirt-concat  "La scadenza degli imminenti appuntamenti istituzionali" )
   (sinvirt-concat  "Il percorso ordinato" )
   (sinvirt-concat  "Il tanto vituperato percorso step-by-step" )
   (sinvirt-concat  "La posizione ancora così distante" )
   (sinvirt-concat  "Lo stesso insieme delle relazioni sindacali" )
   (sinvirt-concat  "La corretta relazione Sindacato-Banca" )
   (sinvirt-concat  "La franchigia aumentata" )
   ))

(defun sinvirt-part-1  ()
  (sinvirt-select
   (sinvirt-concat  "si caratterizza" (sinvirt-choice "profondamente") "per")
   (sinvirt-concat  "privilegia" (sinvirt-choice "senza dubbio"))
   (sinvirt-concat  "prefigura" (sinvirt-choice "tra l'altro"))
   (sinvirt-concat  "riconduce" (sinvirt-choice "pienamente") "a sintesi")
   (sinvirt-concat  "persegue" (sinvirt-choice "esplicitamente"))
   (sinvirt-concat  "estrinseca" )
   (sinvirt-concat  "si propone" )
   (sinvirt-concat  "presuppone" )
   (sinvirt-concat  "porta" (sinvirt-choice "sempre") "avanti")
   (sinvirt-concat  "auspica" )
   (sinvirt-concat  "sostanzia" )
   (sinvirt-concat  "valorizza" (sinvirt-choice "pienamente"))
   ))

(defun sinvirt-part-2 ()
  (sinvirt-select
   (sinvirt-concat  "una" (sinvirt-choice "coordinata") "prova di compattezza e di determinazione" (sinvirt-choice "quali da tempo non si registrava nell'Istituto") )
   (sinvirt-concat  "il ribaltamento della logica" (sinvirt-choice "gestionale") "esistente")
   (sinvirt-concat  "il superamento" (sinvirt-choice "d'impeto") "di ogni ostacolo" (sinvirt-choice "e/o resistenza passiva") )
   (sinvirt-concat  "un organico " (sinvirt-choice "quanto ordinato") "collegamento interdisciplinare" (sinvirt-choice "ed una prassi di democrazia del lavoro") )
   (sinvirt-concat  "la puntuale corrispondenza fra obiettivi " (sinvirt-choice "proposti") "e risorse" (sinvirt-choice "impiegate") )
   (sinvirt-concat  "la verifica " (sinvirt-choice "critica") "degli obiettivi" (sinvirt-choice "istituzionali") "e l'individuazione dei punti qualificanti")
   (sinvirt-concat  "il riorientamento delle linee di tendenza in atto" )
   (sinvirt-concat  "l'accorpamento delle funzioni e il decentramento decisionale" )
   (sinvirt-concat  "la ricognizione del bisogno emergente e della domanda non soddisfatta" )
   (sinvirt-concat  "la riconversione ed articolazione periferica delle nuove mansioni" )
   (sinvirt-concat  "un rapporto coerente e corretto tra strutture e sovrastrutture" )
   (sinvirt-concat  "una riflessione pacata tra tutti gli attori in gioco" )
   (sinvirt-concat  "le prospettive per la produzione di carte valori" )
   (sinvirt-concat  "la vera ragione delle proteste" )
   (sinvirt-concat  "una dirigenza all'altezza di questo ruolo sociale" )
   (sinvirt-concat  "un percorso irto di insidie mortali" )
   (sinvirt-concat  "la sicurezza dei valori in gioco" )
   (sinvirt-concat  "un change-over senza limiti sostanziali" )
   (sinvirt-concat  "uno sviluppo interrotto e senza prospettive" )
   ))

(defun sinvirt-part-3 ()
  (sinvirt-select
   (sinvirt-concat  "senza per questo cambiare la valutazione iniziale" )
   (sinvirt-concat  "alla ricerca di un'appropriata ragione comune" )
   (sinvirt-concat  "nel primario interesse del lavoratori" )
   (sinvirt-concat  "senza pregiudicare l'attuale livello delle prestazioni" )
   (sinvirt-concat  "al di sopra di interessi e pressioni di parte" )
   (sinvirt-concat  "secondo moduli di interdipendenza orizzontale" )
   (sinvirt-concat  "in una visione organica e ricondotta ad unità" )
   (sinvirt-concat  "con criteri non dirigistici" )
   (sinvirt-concat  "al di là delle contraddizioni e difficoltà iniziali" )
   (sinvirt-concat  "in maniera articolata e non totalizzante" )
   (sinvirt-concat  "attraverso i meccanismi della partecipazione democratica" )
   (sinvirt-concat  "senza precostituzione delle risposte" )
   ))

(defun sinvirt-part-4 ()
  (sinvirt-select
   (sinvirt-concat  "facendone una rappresentazione esplicita" )
   (sinvirt-concat  "autorizzando a credere in buona sostanza" )
   (sinvirt-concat  "non nascondendo la testa sotto la sabbia ma costruendo trasparentemente" )
   (sinvirt-concat  "sostanziando e vitalizzando" )
   (sinvirt-concat  "recuperando ovvero rivalutando" )
   (sinvirt-concat  "ipotizzando e preseguendo" )
   (sinvirt-concat  "non assumendo mai come implicito" )
   (sinvirt-concat  "fattualizzando e concretizzando" )
   (sinvirt-concat  "non sottacendo ma anzi puntualizzando" )
   (sinvirt-concat  "potenziando ed incrementando" )
   (sinvirt-concat  "non dando certo per scontato" )
   (sinvirt-concat  "evidenziando ed esplicitando" )
   (sinvirt-concat  "attivando ed incrementando" )
   (sinvirt-concat  "smuovendo in profondità e facendo pervenire in superficie" )
   (sinvirt-concat  "assicurando senza perdere" )
   (sinvirt-concat  "facendo avanzare e migliorando" )
   (sinvirt-concat  "dando impulso e ideando" )
   (sinvirt-concat  "dando propulsione senza per questo insabbiare" )
   (sinvirt-concat  "rivendicando orgogliosamente e completamente" )))

(defun sinvirt-part-5 ()
  (sinvirt-select
   (sinvirt-concat  "con la massima severità possibile" )
   (sinvirt-concat  "in tempi brevi, anzi brevissimi," )
   (sinvirt-concat  "con un occhio di riguardo all'efficienza" )
   (sinvirt-concat  "con l'obiettivo dell'efficacia aziendale" )
   (sinvirt-concat  "senza perseguire altro obiettivo che la qualità" )
   (sinvirt-concat  "nel contesto storico attuale" )
   (sinvirt-concat  "nè troppo nè troppo poco" )
   (sinvirt-concat  "con assunzioni mirate" )
   (sinvirt-concat  "attraverso una osservazione minuziosa della realtà" )
   (sinvirt-concat  "con incrementi economici adeguati" )
   (sinvirt-concat  "senza perdere di vista il comparto bancario privato" )
   (sinvirt-concat  "senza che nessuno possa avanzare dubbi" )
   (sinvirt-concat  "con tutte le cautele del caso" )
   (sinvirt-concat  "senza che le sedi periferiche siano private di compiti pregnanti" )
   (sinvirt-concat  "con incrementi economici rilevantemente simili" )
   (sinvirt-concat  "senza sprechi ma anzi con notevoli risparmi" )
   (sinvirt-concat  "senza levare niente a nessuno" )
   (sinvirt-concat  "con contezza delle diverse variabili in gioco" )
   (sinvirt-concat  "senza sperperare un patrimonio notevole" )
   (sinvirt-concat  "con un occhio di riguardo per le progressioni automatiche" )
   (sinvirt-concat  "per evitare facili avanzamenti automatici" )
   (sinvirt-concat  "in un ottica preventiva e non curativa" )
   (sinvirt-concat  "in un ambito territoriale omogeneo, ai diversi livelli" )
   (sinvirt-concat  "nel rispetto della normativa esistente" )
   (sinvirt-concat  "nel contesto di un sistema integrato" )
   (sinvirt-concat  "quale sua premessa indispensabile e condizionante" )
   (sinvirt-concat  "nella misura in cui ciò sia fattibile" )
   (sinvirt-concat  "con le dovute ed imprescindibili sottolineature" )
   (sinvirt-concat  "in termini di efficacia ed efficienza" )
   (sinvirt-concat  "a monte e a valle della situazione contingente" )
   ))

(defun sinvirt-part-6 ()
  (sinvirt-select
   (sinvirt-concat  "una meritocrazia che sia nei fatti e non nelle parole" )
   (sinvirt-concat  "la tanto ventilata trasparenza" )
   (sinvirt-concat  "quello che si dice ma non si fa" )
   (sinvirt-concat  "una volta per tutte chiarezza" )
   (sinvirt-concat  "un veloce superamento dell'impasse iniziale" )
   (sinvirt-concat  "la tecnica di \"un colpo al cerchio e uno alla botte\"" )
   (sinvirt-concat  "la tecnologia moderna come fonte di ogni bene" )
   (sinvirt-concat  "la rappresentanza sociale in una fase storica di disimpegno" )
   (sinvirt-concat  "una sorta di novità in un ambiente altrimenti stantio" )
   (sinvirt-concat  "la protesta di oltre il 70% dei colleghi" )
   (sinvirt-concat  "la trasparenza degli atti del Governatore" )
   (sinvirt-concat  "il ruolo del Sindacato nelle innovazioni organizzative, dell'orario di lavoro e della formazione" )
   (sinvirt-concat  "la formazione a distanza come canale privilegiato di conoscenza" )
   (sinvirt-concat  "il coinvolgimento one-to-one come risorsa imbattibile di modernità" )
   (sinvirt-concat  "l'inderogabile questione morale" )
   (sinvirt-concat  "una correzione degna delle performance migliori" )
   (sinvirt-concat  "la polemica fine a sé stessa" )
   (sinvirt-concat  "un radicale ripensamento delle relazioni sindacali" )
   (sinvirt-concat  "lo sciopero come forma di lotta estrema" )
   (sinvirt-concat  "la trasparenza di ogni atto gestionale" )
   (sinvirt-concat  "un retrivo atto di prepotenza gestionale" )
   (sinvirt-concat  "un'indispensabile salto di qualità" )
   (sinvirt-concat  "una congrua flessibilità delle strutture" )
   (sinvirt-concat  "l'annullamento di ogni ghettizzazione" )
   (sinvirt-concat  "il coinvolgimento attivo di tutti i lavoratori" )
   (sinvirt-concat  "l'appianamento delle discrepanze e delle discrasie esistenti" )
   (sinvirt-concat  "la ridefinizione di un nuovo modello delle carriere professionali" )
   (sinvirt-concat  "l'adozione di una metodologia differenziata" )
   (sinvirt-concat  "la detecnicizzazione del linguaggio operativo" )
   (sinvirt-concat  "la comune insoddisfazione nelle relazioni sindacali" )
   (sinvirt-concat  "una revisione dello stato dell'arte tecnologico" )
   ))


(defun sinvirt-part-7 ()
  (sinvirt-select
   (sinvirt-concat  "A queste condizioni non è possibile partecipare!" )
   (sinvirt-concat  "Adesso basta!" )
   (sinvirt-concat  "Ancora una volta si torna indietro!" )
   (sinvirt-concat  "Un vero e proprio passo indietro?" )
   (sinvirt-concat  "Non si sa come valutarlo?" )
   (sinvirt-concat  "Cosa è possibile capire, adesso?" )
   (sinvirt-concat  "Come a dire \"Non disturbare il manovratore\"!" )
   (sinvirt-concat  "E allora: chi controlla i controllori?" )
   (shr-image-fetchedsinvirt-concat  "Va da sé che questo non è ottimale." )
   ))

(defun sinvirt-signature ()
  (sinvirt-select
   (sinvirt-concat  "La Segreteria Nazionale" )
   (sinvirt-concat  "Il Direttivo Provinciale" )
   (sinvirt-concat  "La Direzione Provinciale" )
   (sinvirt-concat  "Il Presidente Federale" )
   (sinvirt-concat  "Il Segretario Nazionale" )
   (sinvirt-concat  "Il Comitato Interno)" )
   ))

(global-set-key (kbd "s-i n v i r t") 'sinvirt)
